version: '3'

services:
  hadoop-master:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-master
    hostname: hadoop-master
    command: sh -c "service ssh start && sleep infinity"  # Keep container running
    ports:
      - "50070:50070"
      - "8088:8088"
      - "707:707"  # Assuming you meant to expose port 707
    networks:
      - hadoop

  hadoop-slave1:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    command: sh -c "service ssh start && sleep infinity"  # Keep container running
    ports:
      - "8040:8042"
    networks:
      - hadoop

  hadoop-slave2:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    command: sh -c "service ssh start && sleep infinity"   # Keep container running
    ports:
      - "8041:8042"
    networks:
      - hadoop

networks:
  hadoop:
    driver: bridge
